"use strict";

const workflowStates = [
	"MESSAGE",
	"REPORT",
	"GUARDRAIL_IN",
	"ORCHESTRATOR",
	"PREDICT_MODEL",
	"FAQ_AGENT",
	"REPORT_AGENT",
	"FORMATTER_AGENT",
	"JUDGE_AGENT",
	"GUARDRAIL_OUT",
	"DONE",
	"REJECTED",
	"ERROR",
];

const requestStatuses = ["RECEIVED", "PROCESSING", "COMPLETED", "REJECTED", "FAILED"];

const agentNames = [
	"guardrail_in",
	"orchestrator",
	"predict_model",
	"faq_agent",
	"report_agent",
	"formatter_agent",
	"judge_agent",
	"guardrail_out",
];

module.exports = {
	version: "1.0.0",
	scope: "ai-service-only",
	inputTypes: ["MESSAGE", "REPORT"],
	workflowStates,
	requestStatuses,
	agentNames,
	collections: {
		ai_conversations: {
			collectionName: "ai_conversations",
			purpose: "Represents a logical conversation started by /ai/message or /ai/report.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "conversationId", "inputType", "status"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							inputType: { enum: ["MESSAGE", "REPORT"] },
							status: { enum: requestStatuses },
							subject: { bsonType: ["string", "null"] },
							lastState: { bsonType: ["string", "null"] },
							metadata: { bsonType: ["object", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { conversationId: 1 }, unique: true },
				{ fields: { traceId: 1 }, unique: false },
				{ fields: { status: 1, createdAt: -1 }, unique: false },
			],
			relationships: [{ field: "conversationId", references: "ai_requests.conversationId" }],
		},
		ai_requests: {
			collectionName: "ai_requests",
			purpose: "Stores the public request accepted by the API and the selected entry intent.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "requestId", "conversationId", "inputType", "status", "payload"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							requestId: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							inputType: { enum: ["MESSAGE", "REPORT"] },
							status: { enum: requestStatuses },
							payload: { bsonType: "object" },
							userInput: { bsonType: ["string", "null"] },
							attachments: { bsonType: ["array", "null"] },
							tags: { bsonType: ["array", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { requestId: 1 }, unique: true },
				{ fields: { conversationId: 1, createdAt: -1 }, unique: false },
				{ fields: { inputType: 1, status: 1 }, unique: false },
			],
			relationships: [{ field: "conversationId", references: "ai_conversations.conversationId" }],
		},
		ai_messages: {
			collectionName: "ai_messages",
			purpose: "Stores the chronological message history exchanged with the pipeline.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "messageId", "conversationId", "role", "content"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							messageId: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							role: { enum: ["system", "user", "assistant", "tool"] },
							content: { bsonType: "string" },
							agentName: { bsonType: ["string", "null"] },
							state: { enum: workflowStates },
							tokens: { bsonType: ["object", "null"] },
							extra: { bsonType: ["object", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { messageId: 1 }, unique: true },
				{ fields: { conversationId: 1, createdAt: 1 }, unique: false },
				{ fields: { conversationId: 1, role: 1 }, unique: false },
			],
			relationships: [{ field: "conversationId", references: "ai_conversations.conversationId" }],
		},
		ai_workflow_runs: {
			collectionName: "ai_workflow_runs",
			purpose: "Represents one execution of the internal state machine for a request.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "runId", "conversationId", "requestId", "currentState", "status"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							runId: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							requestId: { bsonType: "string" },
							currentState: { enum: workflowStates },
							status: { enum: requestStatuses },
							path: { bsonType: ["array", "null"] },
							startedAt: { bsonType: ["date", "null"] },
							finishedAt: { bsonType: ["date", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { runId: 1 }, unique: true },
				{ fields: { conversationId: 1, createdAt: -1 }, unique: false },
				{ fields: { requestId: 1 }, unique: false },
			],
			relationships: [
				{ field: "conversationId", references: "ai_conversations.conversationId" },
				{ field: "requestId", references: "ai_requests.requestId" },
			],
		},
		ai_workflow_events: {
			collectionName: "ai_workflow_events",
			purpose: "Stores each state transition, decision, and control signal emitted during execution.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "eventId", "runId", "conversationId", "requestId", "toState", "eventType", "actor"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							eventId: { bsonType: "string" },
							runId: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							requestId: { bsonType: "string" },
							fromState: { enum: workflowStates },
							toState: { enum: workflowStates },
							eventType: { bsonType: "string" },
							actor: { bsonType: "string" },
							reason: { bsonType: ["string", "null"] },
							payload: { bsonType: ["object", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { eventId: 1 }, unique: true },
				{ fields: { runId: 1, createdAt: 1 }, unique: false },
				{ fields: { conversationId: 1, createdAt: 1 }, unique: false },
			],
			relationships: [{ field: "runId", references: "ai_workflow_runs.runId" }],
		},
		ai_agent_decisions: {
			collectionName: "ai_agent_decisions",
			purpose: "Captures the internal decisions made by each agent, including routing and classification.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "decisionId", "runId", "conversationId", "agentName", "state", "decision"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							decisionId: { bsonType: "string" },
							runId: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							agentName: { enum: agentNames },
							state: { enum: workflowStates },
							decision: { bsonType: "string" },
							confidence: { bsonType: ["double", "int", "null"] },
							inputSnapshot: { bsonType: ["object", "null"] },
							outputSnapshot: { bsonType: ["object", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { decisionId: 1 }, unique: true },
				{ fields: { runId: 1, createdAt: 1 }, unique: false },
				{ fields: { conversationId: 1, agentName: 1 }, unique: false },
			],
			relationships: [{ field: "runId", references: "ai_workflow_runs.runId" }],
		},
		ai_final_responses: {
			collectionName: "ai_final_responses",
			purpose: "Stores the final answer returned to the client after guardrails and formatting.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "responseId", "runId", "conversationId", "requestId", "finalState"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							responseId: { bsonType: "string" },
							runId: { bsonType: "string" },
							conversationId: { bsonType: "string" },
							requestId: { bsonType: "string" },
							finalState: { enum: ["DONE", "REJECTED", "ERROR"] },
							answer: { bsonType: ["string", "null"] },
							formattedPayload: { bsonType: ["object", "null"] },
							summary: { bsonType: ["string", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { responseId: 1 }, unique: true },
				{ fields: { runId: 1 }, unique: false },
				{ fields: { conversationId: 1, createdAt: -1 }, unique: false },
			],
			relationships: [{ field: "runId", references: "ai_workflow_runs.runId" }],
		},
		ai_errors: {
			collectionName: "ai_errors",
			purpose: "Stores processing errors, guardrail rejections, and unexpected failures.",
			createOptions: {
				validationLevel: "moderate",
				validationAction: "error",
				validator: {
					$jsonSchema: {
						bsonType: "object",
						required: ["createdAt", "updatedAt", "traceId", "source", "errorId", "severity", "message"],
						properties: {
							createdAt: { bsonType: "date" },
							updatedAt: { bsonType: "date" },
							traceId: { bsonType: "string" },
							tenantId: { bsonType: ["string", "null"] },
							source: { bsonType: "string" },
							errorId: { bsonType: "string" },
							runId: { bsonType: ["string", "null"] },
							conversationId: { bsonType: ["string", "null"] },
							requestId: { bsonType: ["string", "null"] },
							sourceState: { enum: workflowStates },
							severity: { enum: ["info", "warning", "error", "critical"] },
							message: { bsonType: "string" },
							details: { bsonType: ["object", "null"] },
						},
					},
				},
			},
			indexes: [
				{ fields: { errorId: 1 }, unique: true },
				{ fields: { runId: 1, createdAt: -1 }, unique: false },
				{ fields: { severity: 1, createdAt: -1 }, unique: false },
			],
			relationships: [{ field: "runId", references: "ai_workflow_runs.runId" }],
		},
	},
};
