apiVersion: v1
kind: Service
metadata:
  name: ms-artificial-intelligence-service
spec:
  selector:
    app: ms-artificial-intelligence-core 
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080 
  type: LoadBalancer