name: Deploy Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build

      - name: Deploy to Production
        run: echo "comando de deploy aqui quando definir hospedagem"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}