name: Deploy QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build

      - name: Deploy to QA
        run: echo "comando de deploy aqui quando definir hospedagem"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}