name: Deploy QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/537842934721/locations/global/workloadIdentityPools/zera-pool/providers/github-provider'
          service_account: 'github-actions-deploy@zera1405.iam.gserviceaccount.com'

      - uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'autopilot-cluster-1'
          location: 'us-central1'

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/zera1405/repo/ms-artificial-intelligence-core:qa .
          docker push us-central1-docker.pkg.dev/zera1405/repo/ms-artificial-intelligence-core:qa

      - name: Deploy to GKE
        run: |
          sed -i "s|:latest|:qa|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml